### PR TITLE
Ag ren seq modifications

### PR DESCRIPTION
**Pull request by TMAdams**
This makes a few changes to the Ag-RenSeq workflow to bring it closer to the output of Snakemake HISS as well as tweaking some of the run parameters for existing processes

### CODE REVIEW

**Comment by TMAdams** [comment]
TODO:
- Ensure scripts are executable
- Make changes to main.nf (will currently cause conflicts if merged after smrt-renseq assembly)

**Comment by TMAdams** [comment]
Final commit in here is a merge conflict resolution for main.nf

**Comment by TMAdams** [comment]
Optimisation pass has broken kmc syntax, converting to draft while this is fixed

**Comment by TMAdams** [comment]
kmc syntax repaired, java heap size is a recurring issue that may need further fixes as we go on but believe I've caught all the high memory java tasks

**Comment by SwiftSeal** [comment]
altered mem handling (should work?) otherwise lgtm

**Comment by TMAdams** [comment]
Will run a re-test to ensure memory handling works as expected, looks like it should but making sure

**Review by SwiftSeal — APPROVED** [review]

**Pull request merged**
